# Generated by Django 3.2.6 on 2021-08-24 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='internship_report',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='internship_report',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed')], default='New', max_length=9),
        ),
        migrations.AlterField(
            model_name='internship_report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
