# Generated by Django 3.2.6 on 2021-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210824_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_report',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed')], default='', max_length=9),
        ),
    ]
