# Generated by Django 3.2.6 on 2021-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210828_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.DeleteModel(
            name='upload2',
        ),
    ]
