# Generated by Django 3.2.6 on 2021-08-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_internship_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_report',
            name='slug',
        ),
    ]
