# Generated by Django 3.2.6 on 2021-08-30 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210830_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
